### ISSUE TITLE
Fix `build` script failure because of `uglify-js`

### ISSUE THREAD

**Issue by manovotny** [substack/react-starter-hmr#2]
I would have opened a PR, but I was unsure what you wanted to do, but I would be happy to do so if you'd tell me what you'd like to do.

In short, the `npm run build` script is broke because `uglify-js` is not a dependency.

The [`react-starter` project (which this project is based off of) has it](https://github.com/substack/react-starter/blob/58fb825aeed905bfbdbad57e59ac767606fd5eae/package.json#L18), so it should either:

1. be added back as a dependency to this project
2. be removed from the `npm run build` script

**Comment by substack** [comment]
Thanks for the bug report. Fixed in d8b3fcd.
